[2024-06-07T14:11:16.128+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T14:11:16.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-05T00:00:00+00:00 [queued]>
[2024-06-07T14:11:16.163+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-05T00:00:00+00:00 [queued]>
[2024-06-07T14:11:16.164+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-07T14:11:16.179+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_recent_data> on 2024-06-05 00:00:00+00:00
[2024-06-07T14:11:16.186+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T14:11:16.187+0000] {standard_task_runner.py:63} INFO - Started process 235 to run task
[2024-06-07T14:11:16.188+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'fetch_recent_data', 'scheduled__2024-06-05T00:00:00+00:00', '--job-id', '841', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpu15un2ei']
[2024-06-07T14:11:16.189+0000] {standard_task_runner.py:91} INFO - Job 841: Subtask fetch_recent_data
[2024-06-07T14:11:16.236+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-05T00:00:00+00:00 [running]> on host 1dcaa0c0151e
[2024-06-07T14:11:16.337+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='fetch_recent_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-05T00:00:00+00:00'
[2024-06-07T14:11:16.349+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T14:11:16.387+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-07T14:11:16.517+0000] {logging_mixin.py:188} INFO - Data fetch complete
[2024-06-07T14:11:16.518+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-07T14:11:16.519+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T14:11:16.528+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=fetch_recent_data, run_id=scheduled__2024-06-05T00:00:00+00:00, execution_date=20240605T000000, start_date=20240607T141116, end_date=20240607T141116
[2024-06-07T14:11:16.562+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-07T14:11:16.579+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-07T14:11:16.581+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
