[2024-06-05T17:08:47.771+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T17:08:47.794+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table manual__2024-06-05T16:35:59.651756+00:00 [queued]>
[2024-06-05T17:08:47.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table manual__2024-06-05T16:35:59.651756+00:00 [queued]>
[2024-06-05T17:08:47.806+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 7
[2024-06-05T17:08:47.820+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_postgres_table> on 2024-06-05 16:35:59.651756+00:00
[2024-06-05T17:08:47.828+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=328) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T17:08:47.830+0000] {standard_task_runner.py:63} INFO - Started process 331 to run task
[2024-06-05T17:08:47.830+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'create_postgres_table', 'manual__2024-06-05T16:35:59.651756+00:00', '--job-id', '731', '--raw', '--subdir', 'DAGS_FOLDER/pipe.py', '--cfg-path', '/tmp/tmpxbf24cv5']
[2024-06-05T17:08:47.832+0000] {standard_task_runner.py:91} INFO - Job 731: Subtask create_postgres_table
[2024-06-05T17:08:47.890+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.create_postgres_table manual__2024-06-05T16:35:59.651756+00:00 [running]> on host 6dbcf9923072
[2024-06-05T17:08:47.994+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T16:35:59.651756+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T16:35:59.651756+00:00'
[2024-06-05T17:08:47.996+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T17:08:48.010+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T17:08:48.028+0000] {sql.py:470} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS potential_customers (
        UserID TEXT,
        basket_icon_click INTEGER,
        basket_add_list INTEGER,
        basket_add_detail INTEGER,
        sort_by INTEGER,
        image_picker INTEGER,
        account_page_click INTEGER,
        promo_banner_click INTEGER,
        detail_wishlist_add INTEGER,
        list_size_dropdown INTEGER,
        closed_minibasket_click INTEGER,
        checked_delivery_detail INTEGER,
        checked_returns_detail INTEGER,
        sign_in INTEGER,
        saw_checkout INTEGER,
        saw_sizecharts INTEGER,
        saw_delivery INTEGER,
        saw_account_upgrade INTEGER,
        saw_homepage INTEGER,
        device_mobile INTEGER,
        device_computer INTEGER,
        device_tablet INTEGER,
        returning_user INTEGER,
        loc_uk INTEGER,
        ordered INTEGER,
        created_at TIMESTAMP
    );
    , parameters: None
[2024-06-05T17:08:48.037+0000] {logging_mixin.py:188} INFO - Create table successful
[2024-06-05T17:08:48.038+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T17:08:48.039+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T17:08:48.051+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=create_postgres_table, run_id=manual__2024-06-05T16:35:59.651756+00:00, execution_date=20240605T163559, start_date=20240605T170847, end_date=20240605T170848
[2024-06-05T17:08:48.085+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T17:08:48.111+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T17:08:48.113+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
