[2024-06-07T14:02:03.343+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T14:02:03.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.download_and_insert_data scheduled__2024-06-06T00:00:00+00:00 [queued]>
[2024-06-07T14:02:03.387+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.download_and_insert_data scheduled__2024-06-06T00:00:00+00:00 [queued]>
[2024-06-07T14:02:03.388+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-07T14:02:03.407+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_insert_data> on 2024-06-06 00:00:00+00:00
[2024-06-07T14:02:03.416+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T14:02:03.418+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-06-07T14:02:03.418+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'download_and_insert_data', 'scheduled__2024-06-06T00:00:00+00:00', '--job-id', '825', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp_oyvnvtx']
[2024-06-07T14:02:03.420+0000] {standard_task_runner.py:91} INFO - Job 825: Subtask download_and_insert_data
[2024-06-07T14:02:03.501+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.download_and_insert_data scheduled__2024-06-06T00:00:00+00:00 [running]> on host 1dcaa0c0151e
[2024-06-07T14:02:03.781+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='download_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-06T00:00:00+00:00'
[2024-06-07T14:02:03.783+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T14:02:07.584+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-07T14:02:12.635+0000] {logging_mixin.py:188} INFO - Data insertion complete
[2024-06-07T14:02:12.638+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-07T14:02:12.639+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T14:02:12.663+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=download_and_insert_data, run_id=scheduled__2024-06-06T00:00:00+00:00, execution_date=20240606T000000, start_date=20240607T140203, end_date=20240607T140212
[2024-06-07T14:02:12.736+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-07T14:02:12.826+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-07T14:02:12.830+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
