[2024-06-05T16:46:54.701+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T16:46:54.777+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T16:46:54.801+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T16:46:54.802+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T16:46:54.849+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_recent_data> on 2024-06-04 00:00:00+00:00
[2024-06-05T16:46:54.863+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T16:46:54.869+0000] {standard_task_runner.py:63} INFO - Started process 77 to run task
[2024-06-05T16:46:54.870+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'fetch_recent_data', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '716', '--raw', '--subdir', 'DAGS_FOLDER/pipe.py', '--cfg-path', '/tmp/tmpey9r6jvv']
[2024-06-05T16:46:54.874+0000] {standard_task_runner.py:91} INFO - Job 716: Subtask fetch_recent_data
[2024-06-05T16:46:55.002+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [running]> on host 0c39f87f9155
[2024-06-05T16:46:55.187+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='fetch_recent_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-06-05T16:46:55.189+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T16:46:55.205+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T16:46:55.306+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T16:46:55.308+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipe.py", line 118, in fetch_recent_data_to_csv
    df.to_csv('/opt/airflow/data/recent_data.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/data'
[2024-06-05T16:46:55.334+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_postgres, task_id=fetch_recent_data, run_id=scheduled__2024-06-04T00:00:00+00:00, execution_date=20240604T000000, start_date=20240605T164654, end_date=20240605T164655
[2024-06-05T16:46:55.357+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 716 for task fetch_recent_data (Cannot save file into a non-existent directory: '/opt/***/data'; 77)
[2024-06-05T16:46:55.380+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T16:46:55.409+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T16:46:55.412+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T17:17:06.218+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T17:17:06.258+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T17:17:06.270+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T17:17:06.271+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T17:17:06.297+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_recent_data> on 2024-06-04 00:00:00+00:00
[2024-06-05T17:17:06.308+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T17:17:06.311+0000] {standard_task_runner.py:63} INFO - Started process 106 to run task
[2024-06-05T17:17:06.310+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'fetch_recent_data', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '741', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpndjlrtt1']
[2024-06-05T17:17:06.312+0000] {standard_task_runner.py:91} INFO - Job 741: Subtask fetch_recent_data
[2024-06-05T17:17:06.379+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [running]> on host 68d2d1c90970
[2024-06-05T17:17:06.554+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='fetch_recent_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-06-05T17:17:06.559+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T17:17:06.588+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T17:17:06.665+0000] {logging_mixin.py:188} INFO - Data fetch complete
[2024-06-05T17:17:06.667+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T17:17:06.668+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T17:17:06.686+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=fetch_recent_data, run_id=scheduled__2024-06-04T00:00:00+00:00, execution_date=20240604T000000, start_date=20240605T171706, end_date=20240605T171706
[2024-06-05T17:17:06.768+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T17:17:06.816+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T17:17:06.819+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
