[2024-06-07T14:02:16.506+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T14:02:16.536+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-06T00:00:00+00:00 [queued]>
[2024-06-07T14:02:16.546+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-06T00:00:00+00:00 [queued]>
[2024-06-07T14:02:16.547+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-07T14:02:16.571+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_recent_data> on 2024-06-06 00:00:00+00:00
[2024-06-07T14:02:16.580+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T14:02:16.582+0000] {standard_task_runner.py:63} INFO - Started process 81 to run task
[2024-06-07T14:02:16.583+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'fetch_recent_data', 'scheduled__2024-06-06T00:00:00+00:00', '--job-id', '827', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpxrqvhcog']
[2024-06-07T14:02:16.586+0000] {standard_task_runner.py:91} INFO - Job 827: Subtask fetch_recent_data
[2024-06-07T14:02:16.652+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-06T00:00:00+00:00 [running]> on host 1dcaa0c0151e
[2024-06-07T14:02:16.796+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='fetch_recent_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-06T00:00:00+00:00'
[2024-06-07T14:02:16.797+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T14:02:16.809+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-07T14:02:16.998+0000] {logging_mixin.py:188} INFO - Data fetch complete
[2024-06-07T14:02:17.001+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-07T14:02:17.002+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T14:02:17.012+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=fetch_recent_data, run_id=scheduled__2024-06-06T00:00:00+00:00, execution_date=20240606T000000, start_date=20240607T140216, end_date=20240607T140217
[2024-06-07T14:02:17.038+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-07T14:02:17.068+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-07T14:02:17.070+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
